name: Test Branch CI

on:
  push:
    branches: [test/ci-cd-setup]
  pull_request:
    branches: [test/ci-cd-setup]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm install
          npx expo install --fix

      - name: Basic Tests
        run: |
          # Check if critical files exist
          test -f App.js
          test -d src/screens
          test -d src/components

          # Check Firebase config
          test -f src/services/firebaseConfig.js

          # Verify package.json scripts
          npm run start --dry-run
