export default {
    KNOWN_FACT: 'Cameron is a cute poes',


    pluto_title: "PLUTO",
    full_name_placeholder: "FULL NAME",
    email_placeholder: "EMAIL",
    phone_placeholder: "PHONE NUMBER",
    password_placeholder: "PASSWORD",
    address_placeholder: "HOME ADDRESS",
    login_button: "LOGIN",
    register_button: "REGISTER",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    register_link: "Register here.",
    login_link: "Login here.",

    //Filter Page//
    title: "ANIMAL FILTERS",
    lookingForLabel: "Looking for:",
    dogsButton: "DOGS",
    catsButton: "CATS",
    breedLabel: "Breed:",
    anyBreed: "Any",
    furColorLabel: "Fur Color:",
    selectFurColor: "Select Fur Color",
    maximumDistanceLabel: (maxDistance) => `Maximum distance: ${maxDistance} km`,
    ageRangeLabel: (min, max) => `Age range: ${min} - ${max} years`,
    activityLevelLabel: (activityLevel) => `Activity level: ${activityLevel}`,
    sizeLabel: (size) => `Size: ${size}`,
    applyFilterButton: "Apply",
    applyFiltersMessage: "Filters applied!",
    closeButton: "Close",
    selectFurColors: "Select Fur Colors:",


    //Add Animal Page//
    addAnimalTitle: "Add New Animal",
    dogToggle: "Dogs",
    catToggle: "Cats",
    nameLabel: "Name",
    namePlaceholder: "Enter Animal Name",
    breedPlaceholder: "Enter Breed",
    ageLabel: "Age",
    agePlaceholder: "Enter Age",
    biographyLabel: "Biography",
    biographyPlaceholder: "Write a brief biography",
    couchCushion: "Couch Cushion",
    moderatelyActive: "Moderately Active",
    highlyActive: "Highly Active",
    doneButton: "Done",
    cancelButton: "Cancel",
    uploadImageText: "Upload Image",
    maxImagesWarning: "You can upload up to 7 images.",
    minImagesWarning: "Please upload at least 3 images.",
    removeImageButton: "Remove",
    selectSpecies: "Select Species:",
    selectBreed: "Select Breed:",
    selectFur: "Select Fur Color:",

    // User Settings page
    user_settings: {
        user_name: "User Name:",
        location: "Location:",
        your_details_title: "Your Details:",
        name_label: "Name:",
        surname_label: "Surname:",
        email_label: "Email:",
        password_label: "Password:",
        confirm_password_label: "Confirm Password:",
        privacy_title: "Privacy:",
        push_notifications: "Push Notifications",
        update_button: "Update",
        logout_button: "Logout",
        sample_text: "Sample Text",
        password_placeholder: "********",
        confirm_password_placeholder: "********"
    },

    // Shelter Settings page
    shelter_settings: {
        shelter_name: "Shelter Name:",
        shelter_location: "Location:",
        shelter_email: "Email:",
        shelter_tel: "Telephone:",
        shelter_password: "Password:",
        shelter_confirm_password: "Confirm Password:",
        shelter_details_title: "Shelter Details:",
        shelter_update_button: "Update Shelter",
        shelter_logout_button: "Logout Shelter",
        shelter_sample_text: "Sample Shelter Info",
        shelter_password_placeholder: "********",
        shelter_confirm_password_placeholder: "********",
        shelter_image: "Shelter Image:",
        shelter_privacy_title: "Privacy:",
        shelter_push_notifications: "Push Notifications"
    }
};